export * from "./isConnectableData";
export * from "./isExportable";
export * from "./isFillableData";
export * from "./isItemableData";
export * from "./isSelectableData";
export * from "./isShape";
export * from "./isStrokableData";
export * from "./isTextableData";
export * from "./isTransformativeData";
